backend/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes(['register' => false]);

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth', 'admin']], function(){
    Route::get('/customers', 'HomeController@customers');
    Route::delete('/customers/{user}', 'HomeController@deleteCustomer')->name('customers.destroy');
    Route::get('/orders', 'OrderController@index');
    Route::put('/orders/{order}', 'OrderController@markDispatched')->name('orders.dispatch');
    Route::resource('items','ItemController')->except('show');
});

backend/app/Item.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Item extends Model
{
    protected $fillable = ['name', 'description', 'image', 'price'];
}

backend/app/Http/Controllers/Api/ItemController.php
<?php

namespace App\Http\Controllers\Api;

use App\Item;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class ItemController extends Controller
{
    public function index(Request $request)
    {
        $items = Item::skip($request->skip ?? 0)->take(20)->get();

        return $items;
    }
}

backend/app/Http/Controllers/ItemController.php
<?php

namespace App\Http\Controllers;

use App\Item;
use Illuminate\Http\Request;

class ItemController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $items = Item::latest()->paginate(30);
        return view('items.index', \compact('items'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('items.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $data = $this->validate($request, [
            'name' => 'required|string|max:100|unique:items',
            'description' => 'required|string|max:255',
            'image' => 'required',
            'price' => 'required|numeric'
        ]);
        Item::create($data);
        session()->flash('success', 'Item created');
        return back();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function edit(Item $item)
    {
        return view('items.edit', compact('item'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Item $item)
    {
        $data = $this->validate($request, [
            'name' => 'required|string|max:100|unique:items,name,'.$item->id,
            'description' => 'required|string|max:255',
            'image' => 'required',
            'price' => 'required|numeric'
        ]);

        $item->update($data);
        session()->flash('success', "{$item->name} updated");

        return back();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Item  $item
     * @return \Illuminate\Http\Response
     */
    public function destroy(Item $item)
    {
        $item->delete();
        session()->flash('success', "{$item->name} deleted");
        return back();
    }
}

backend/resources/views/items/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="w-75 mx-auto">
        <div class="card">
            <div class="card-header">
                Add new item
            </div>
            <div class="card-body">
                <form action="{{ route('items.store') }}" method="post">
                    @csrf
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" placeholder="Enter item name here" name="name"
                            value="{{ old('name') }}">
                        @if ($errors->has('name'))
                        <strong class="text-danger">{{ $errors->first('name') }}</strong>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <div class="input-group">
                            <label for="image"></label>
                            <span class="input-group-btn">
                                <a id="lfm" data-input="thumbnail" data-preview="holder"
                                    class="btn btn-primary text-white">
                                    <i class="fa fa-picture-o"></i> Choose
                                </a>
                            </span>
                            <input id="thumbnail" class="form-control" type="text" name="image"
                                placeholder="Select an image for item" value="{{ old('image') }}">
                        </div>
                        <img id="holder" style="margin-top:15px;max-height:100px;" src="{{ old('image') }}">
                        @if ($errors->has('image'))
                        <strong class="text-danger">{{ $errors->first('image') }}</strong>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" class="form-control" name="description"
                            placeholder="Enter item description">{{ old('description') }}</textarea>
                        @if ($errors->has('description'))
                        <strong class="text-danger">{{ $errors->first('description') }}</strong>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="number" placeholder="Enter price here" name="price" value="{{ old('price') }}"
                            class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-sm btn-primary btn-block">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@section('js')
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>
<script>
    $('#lfm').filemanager('image');
</script>
@endsection

backend/resources/views/items/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="w-75 mx-auto">
        <div class="card">
            <div class="card-header">
                Edit {{ $item->name }}
            </div>
            <div class="card-body">
                <form action="{{ route('items.update', $item->id) }}" method="post">
                    @csrf
                    @method('put')
                    <div class="form-group">
                        <label for="name">Name</label>
                        <input type="text" class="form-control" placeholder="Enter item name here" name="name"
                            value="{{ old('name',$item->name) }}">
                        @if ($errors->has('name'))
                        <strong class="text-danger">{{ $errors->first('name') }}</strong>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="image">Image</label>
                        <div class="input-group">
                            <label for="image"></label>
                            <span class="input-group-btn">
                                <a id="lfm" data-input="thumbnail" data-preview="holder"
                                    class="btn btn-primary text-white">
                                    <i class="fa fa-picture-o"></i> Choose
                                </a>
                            </span>
                            <input id="thumbnail" class="form-control" type="text" name="image"
                                placeholder="Select an image for item" value="{{ old('image', $item->image) }}">
                        </div>
                        <img id="holder" style="margin-top:15px;max-height:100px;"
                            src="{{ old('image',$item->image) }}">
                        @if ($errors->has('image'))
                        <strong class="text-danger">{{ $errors->first('image') }}</strong>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="description">Description</label>
                        <textarea name="description" id="description" class="form-control" name="description"
                            placeholder="Enter item description">{{ old('description', $item->description) }}</textarea>
                        @if ($errors->has('description'))
                        <strong class="text-danger">{{ $errors->first('description') }}</strong>
                        @endif
                    </div>
                    <div class="form-group">
                        <label for="price">Price</label>
                        <input type="number" placeholder="Enter price here" name="price"
                            value="{{ old('price', $item->price) }}" class="form-control">
                    </div>
                    <div class="form-group">
                        <input type="submit" class="btn btn-sm btn-primary btn-block">
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>
@stop

@section('js')
<script src="/vendor/laravel-filemanager/js/lfm.js"></script>
<script>
    $('#lfm').filemanager('image');

</script>
@endsection

backend/resources/views/items/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="card">
        <div class="card-header">
            <div class="d-flex justify-content-between">
                <div>
                    All Items
                </div>
                <a href="{{ route('items.create') }}" class="btn btn-sm btn-success">Add new</a>
            </div>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Name</th>
                            <th>Description</th>
                            <th>Price</th>
                            <th colspan="2" class="text-center">Actions</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach ($items as $item)
                        <tr>
                            <td>{{ $loop->iteration }}</td>
                            <td>{{ $item->name }}</td>
                            <td>{{ $item->description }}</td>
                            <td>{{ $item->price }}</td>
                            <td>
                                <a href="{{ route('items.edit', $item->id) }}" class="btn btn-primary btn-sm">edit</a>
                            </td>
                            <td>
                                <button type="button" class="btn btn-sm btn-danger" data-toggle="modal"
                                    data-target="#delete{{ $item->id }}">
                                    delete
                                </button>
                                <div class="modal" id="delete{{ $item->id }}">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <h4 class="modal-title">Are you sure you want to remove
                                                    {{ $item->name }} ?</h4>
                                                <button type="button" class="close"
                                                    data-dismiss="modal">&times;</button>
                                            </div>
                                            <div class="modal-footer">
                                                <form action="{{ route('items.destroy',$item->id) }}" method="post">
                                                    @csrf
                                                    @method('delete')
                                                    <button type="button" class="btn btn-sm btn-primary" data-dismiss="modal">Close</button>
                                                    <button type="submit" class="btn btn-sm btn-danger">Delete</button>
                                                </form>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
        <div class="d-flex justify-content-center">
            {{ $items->links() }}
        </div>
    </div>
</div>
@endsection